spring.application.name=attendance_system
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=attendance_system;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2

spring.datasource.username=sa
spring.datasource.password=Anan4002@


server.port=8081
logging.level.org.springframework.jdbc=DEBUG
